export default {
  API_BASE_URL: 'https://api.coinmarket.com',
  FETCHING_COIN_DATA: 'FETCHING_COIN_DATA',
  FETCHING_COIN_DATA_SUCCESS: 'FETCHING_COIN_DATA_SUCCESS',
  FETCHING_COIN_DATA_FAIL: 'FETCHING_COIN_DATA_FAIL',
};
